name: miltv_universal
description: MILTV — multiplatform native streaming application.
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.3
  crypto: ^3.0.6
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_android_video: ^1.0.7
  media_kit_libs_macos_video: ^1.0.7
  media_kit_libs_linux: ^1.1.3
  media_kit_libs_windows_video: ^1.0.11
  supabase_flutter: ^2.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
